name: On push ami build with Packer workflow
on:
  push:
    branches:
      - main
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v2
      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ami.json

      # build artifact
      - name: Build Artifact
        uses: operatehappy/packer-github-actions@master
        with:
          command: build \
            -var "aws_region=${AWS_REGION}" \
            -var "aws_access_key=${AWS_ACCESS_KEY}" \x
            -var "aws_secret_key=${AWS_SECRET_KEY}" \
            -var "subnet_id=${SUBNET_ID}" \
            ami.json
          arguments: "-color=false -on-error=abort"
