name: On push ami build with Packer workflow
on:
  push:
    branches:
      - main
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
      - uses: actions/checkout@v2
      # validate templates
      - name: Validate Template
        uses: actions/ashokaparna@main
        with:
          command: validate
          arguments: -syntax-only
          target: ami.json

      # build artifact
      - name: Build Artifact
        uses: actions/ashokaparna@main
        with:
          command: build
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          subnet_id: ${{ secrets.SUBNET_ID}}
          target: ami.json
          arguments: "-color=false -on-error=abort"
