name: On push ami build with Packer workflow
on:
  push:
    branches:
      - main
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # validate templates
      - name: Validate Template
        uses: operatehappy/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: ami.json

      # build artifact
      - name: Build Artifact
        uses: operatehappy/packer-github-actions@master
        with:
          command: build \
          -var 'aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}' \
          -var 'aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
          -var 'aws_region=${{ secrets.AWS_SECRET_ACCESS_KEY }}' \
          -var 'subnet_id=${{ secrets.SUBNET_ID}}' \
          ami.json
          arguments: "-color=false -on-error=abort"
