name: On push ami build with Packer workflow
on:
  push:
    branches:
      - main
      - a4
jobs:
  packer:
    runs-on: ubuntu-latest
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # install packer
      - name: Install packer
        run: curl -o packer.zip https://releases.hashicorp.com/packer/1.3.3/packer_1.3.3_linux_amd64.zip && unzip packer.zip

      # validate using packer
      - name: Validate ami.json using packer
        run: packer validate ami.json

      # build ami using packer
      - name: Build ami
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{secrets.AWS_REGION}}
          SUBNET_ID: ${{secrets.SUBNET_ID}}

        run: packer build -var 'aws_access_key=AKIA4ARP56NCB6FE32MI' -var 'aws_secret_key=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' -var 'aws_region=us-east-1' -var 'subnet_id=subnet-a2c780ef' ami.json
